pointcloud_to_laserscan:
  ros__parameters:
    target_frame: base_footprint
    transform_tolerance: 0.10
    min_height: 0.05
    max_height: 0.55
    angle_min: -3.141592653589793
    angle_max: 3.141592653589793
    angle_increment: 0.008726646259971648
    queue_size: 1
    scan_time: 0.06666666666666667
    range_min: 0.25
    range_max: 8.0
    use_inf: true
